spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobidic_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mobidic_test
    password: mobidic_test
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: f825308ac5df56907db5835775baf3e4594526f127cb8d9bca70b435d596d424
  exp: 86400000

whisper:
  flask-server-url: http://localhost:5000
jasypt:
  encryptor:
    password: f04f3e3f0b8c1fe1bed17faf3314ecb3d066b80439aeb13a58e7292695274119